version: '3'

services:
  react-app: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
# second service for the tests instead of attaching to running container and launching npm run test
# but we won't have an opportunity to attach to the running container and manipulate with STDIN/OUT
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    # override starting command, written in Dockerfile.dev
    command: ["npm", "run", "test"]